# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pipenv
        name: Install pipenv
        entry: bash -c 'pipenv install --skip-lock --dev'
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
      - id: unittest
        name: Run unit tests (unittest)
        entry: bash -c 'cd packaging-tools && pipenv run python3 -m unittest'
        language: system
        pass_filenames: false
        always_run: true
        fail_fast: true
      - id: flake8
        name: Check PEP8 compliance (flake8)
        # Disable E203 for compatibility with blackformatter, and W503 as it goes against PEP8
        # Disable checks that are not relevant to this patch, they will be introduced later
        entry: bash -c 'pipenv run python3 -m flake8 --max-line-length=99 --ignore=E203,E501,W503 "$@"'
        language: system
        types: [python]
        fail_fast: true
